name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build
